### ISSUE TITLE
Copyright year out of date

### ISSUE THREAD

**Issue by robzwolf** [ducompsoc/website#88]
Copyright year in the footer says 2016-2017. Pls correct to a dynamic year.

**Comment by AlistairMadden** [comment]
See pull request #89

**Comment by robzwolf** [comment]
Have we just hard-coded `2018` in the backend now...? 😂  Shouldn't we be doing something more dynamic like `new Date().getFullYear()`?

**Comment by AlistairMadden** [comment]
Whoops. Yes, you're exactly right @robzwolf. It's correct in the docs :)
