### ISSUE TITLE
Exec team needs updating on Team page

### ISSUE THREAD

**Issue by robzwolf** [ducompsoc/website#91]
New exec is as follows:

**President** 
> Robbie Jakob-Whitworth
> _In charge of overseeing everything in the society._

**Treasurer** 
> Jessica Ng
> _Manages CompSoc's finances._

**Secretary** 
> Vivek Mehta
> _Responsible for working with sponsors and other organisations to ensure CompSoc runs smoothly, handling contracts and paperwork._

**Education Officer** 
> Mitchel Starkie
> _In charge of educating both society members and/or those interested in programming but with little technical experience._

**Publicity Officer** 
> Kat Strachan
> _In charge of the website content, social media, the mailing list, and promoting the society around the university._

**Technical Web Officer** 
> Soumya Singh
> _Works with the Publicity Officer to manage the technical side of the website._

**Events Officer** 
> Karl Southern
> _Works with sponsors and guest speakers to organise talks and workshops._

**Officers without Portfolio** 
> Dmytro Drobisher
> Henrike Gbinigie
> _General helping hands for all parts of the society._

**Comment by AlistairMadden** [comment]
Do we have pictures for new exec (or new pictures for old exec :laughing:)?

**Comment by robzwolf** [comment]
I'll hunt some down!

**Comment by AlistairMadden** [comment]
See #100

**Comment by AlistairMadden** [comment]
Closed by #100
