### ISSUE TITLE
Exec pictures are all broken

### ISSUE THREAD

**Issue by robzwolf** [ducompsoc/website#93]
Because they use URLs `./img/team/` whereas we'd need either `../img/team/` or just `/img/team/`

**Comment by AlistairMadden** [comment]
A couple of places around the interwebs have suggested absolute links (i.e. https://www.compsoc.tech/img/team/Alistair%20Madden.png) would actually be better from an SEO point of view. My thoughts are to keep links relative and add another step which builds the website for production with absolute links. Probably most sensibly done via NPM as not to add another component to the site.
